### ISSUE TITLE
Louisville crime data

### ISSUE THREAD

**Issue by ehbick01** [Data4Democracy/usa-dashboard#13]
https://data.louisvilleky.gov/dataset/crime-data

**Comment by bobpore** [comment]
Just submitted a pull request with Louisville data.

**Comment by schnuerle** [comment]
I'm working on fixing an issue mentioned in the comments here: https://github.com/Data4Democracy/usa-dashboard/blob/master/louisville/louisville_crime_data_parser_lpd_source.py

Namely that the 2009 currently contains 2012 data, so 2009 data is missing.

**Comment by schnuerle** [comment]
This was fixed a while ago FYI. 2009 data is in 2009 data file.  Forgot to update this issue earlier.

**Comment by devinaconley** [comment]
Great, closing this.
